### ISSUE TITLE
Authentication/Authorization Model

### ISSUE THREAD

**Issue by lennartkoopmann** [lennartkoopmann/nzyme#795]
### Feature Description

Remove old single-user authorization model and replace with a full multi-tentant capable solution.

### Design Considerations

* Must stay easy to use, especially for small setups.
* Create a high level of trust for the user. Make it easy to confirm that the configuration does what the user expects it to do, and let others cross-confirm what is set up.
* Single mechanism/chokepoint/logic implementation

#### General

- [x] Send email / notify user on any password, MFA change
- [x] Detect unusual amounts of login attempts for same user (threshold is 5)
  - [x] Alert respective org admins, all super admins 
  - [x] Throttle logins for user
  - [x] Unthrottle after successful login
- [x] A new nzyme setup always comes with a default organization structure setup
- [x] Remove roles from UI
- [x] Rename "Authentication & Authorization" to just "Organizations"/"Organization" because it does more now

#### Passwords

- [x] at least 12 characters in length, max 128 characters
- [x] Work with unicode characters, for example emojis
- [x] Hashes are salted with at least 32 bits, with an individual salt per hash
- [x] Use strong Argon2 hashes for salted passwords
- [x] No rules that require a specific set of characters (at least one number, special char etc)
- [x] No enforced credential rotation
- [x] Password input box allows to temporarily unmask password
- [x] Can be reset by administrators / users with according privileges

#### MFA

- [x] Must be pluggable to easily support additional methods in the future
- [x] No weak methods like email or SMS
- [x] TOTP
- [x] Backup codes are stored and the user is prompted to store them in a safe location
- [x] A user using a backup code triggers notifications to user and organization administrators
- [x] Backup codes must have sufficient entropy of more than 112 bit
- [x] Can be reset by organization administrators in case of a user losing a MFA device, for example in a theft scenario
- [x] Re-use of valid MFA codes is rejected, logged, organization administrator and user are notified. 
  - [x] Detect
  - [x] Alert

#### Sessions

- [x] Reset/invalidate all sessions on any credential or MFA change
- [x] List all existing sessions
- [x] Allow to manually reset/invalidate all existing sessions
- [x] Token has at least 64 bits of entropy
- [x] Reset/Invalidate after 15 minutes of activity or 12 hours after creation
- [x] Store in browser local storage, avoid cookies

### Critical Areas for Security

* Needs extensive testing
* Carefully review and implement related areas of #794 
* Audit logging is critical

#### Role / Organizational Structure

The goal of the design is to combine flexibility and security with an easy to understand model of resulting permissions for users. A user should understand what permissions they have, and administrators should easily understand what permissions are set up and if they are correct.

There are four layers for grouping access into pre-defined abstractions that are easy to understand:

1. nzyme (the entire nzyme cluster/setup) (Example: A hosting provider, any company or deployment owner)
2. Organization (Example: a MSSP, ACME Corp)
3. Tenant (Example: Client of an MSSP, Security Team of ACME Corp, Division of ACME Corp)
4. Tap (Example: Tap deployed at a MSSP customer, tap deployed at ACME Corp)

The resulting default roles are:

* **Super Administrator**
  * Full access to all data and administrative functions
  * Responsible for scaling and ensuring smooth operation of nzyme, as well as high level setup/configuration 
* **Organization Administrator**
  * Full access to all data of organization
  * Access to configuration of organization. For example: alert methods, detection rules, etc, 
  * Can set up tenants in organization
* **Organization User**
  * Full access to all data of organization
* **Tenant Administrator**
  * Full access to configuration of tenant. For example: alert methods, detection rules, etc
  * Can set up taps in tenant
* **Tenant User**
  * Full access to all data of tenant
* **Tap User**
  * Full access to all data of a tap
 
![Image](https://user-images.githubusercontent.com/35022/229663988-c9bebb4f-f71b-470d-859c-993cb00504b2.png)

Each default role has a set of permissions applied.

Custom roles can be created and assigned any set of permissions. The permissions inherit access scope just like the default permissions. For example, assigning the `REGENERATE_TAP_SECRET` to a `TENANT` scope user will allow users with that role to only regenerate all tap secrets of taps that belong to their tenant.

A user can have multiple roles but only one scope assigned.

#### Permission Checks

All permission checks happen on a resource-basis. Each resource requires a permission and a filter checks if the `Principal` has the required permissions to request the resource. Additionally, some resources have to perform further checks for a second layer of permissions: For example, a request for data will have to check if the requested tap scope is allowed for the `Principal`.

Frontend checks are purely cosmetic and only make sure that a user is not presented with actions they cannot perform anyways.

### Tasks / Tickets

- [x] Plan/draw authentication structure/flow in this ticket
- [x] #797 
- [x] #798 
- [x] #803
- [x] #784 
- [x] #802  
- [x] #800
- [x] #801 
- [x] #808 

### Threat Model

| STRIDE | Identified Threat | Mitigation
| --- | --- |  --- |
| Spoofing| No threats identified| n/a |
| Tampering| No threats identified| n/a|
| Repudication| Unauthorized actions might be taken by users with high levels of privilege | Audit Log captures and stores all actions in an integrity-safe way, including user login action with underlying metadata like source IP address.|
| Information Disclosure| A programming/logic error might lead to unintended disclosure of information| Unit tests and a single point of authentication/authorization logic.|
| Information Disclosure| A mistake by a user with elevated privileges when assigning access rights leads to unintended disclosure of information by assigning a too elevated level of permissions.| Permission model must be easy to understand and easy to verify.|
| Denial of Service| Lockout of user(s) by triggering incremental response offset through failed logins | Administrators can reset incremental offset level|
| Elevation of Privileges|  A programming/logic error might lead to unintended elevation of privileges| Unit tests and a single point of authentication/authorization logic.|
| Elevation of Privileges|  A mistake by a user with elevated privileges when assigning access rights leads to unintended elevation of privileges by assigning a too elevated level of permissions.| Permission model must be easy to understand and easy to verify.|

- [x] STRIDE Analysis & Mitigation techniques table
- [ ] Published

### Documentation

- [ ] High-level architecture, data flows, trust boundaries, connected remote services
- [ ] Are there changes compared to previous versions?
- [ ] Changelog updated
- [ ] Published
