### ISSUE TITLE
Events / Notification System

### ISSUE THREAD

**Issue by lennartkoopmann** [lennartkoopmann/nzyme#810]
- [x] Remove old alerts system
- [x] ~~Tests~~ -> moved to tasks. wait for final revision and impl of this
- [x] Confirm multi-node part of this
- [x] ~~Build email callback~~ -> moved to #813 
- [x] ~~Build WASM callback~~ -> moved to #814
- [x] ~~Create tickets for remaining callbacks~~
- [x] Fix email form validation
- [x] ~~Implement tab nav instead of button to org events mgmt~~ -> moved to #795 
- [x] Test whole thing as orgadmin, tenant user
- [x] Final permission checks
  - [x] No leaks between orgs or orgs/superadmin views
  - [x] Can't access superadmin types etc 
  - [x] Org event table only shows org events

### Additional Events

- [x] Superadmin created
- [x] Superadmin password change
- [x] Superadmin MFA reset
- [x] Superadmin MFA code used
- [x] Superadmin MFA code re-used 

### Subscriptions

- [x] List all system events
  - [x] Filter: Categories
  - [x] Pagination 
- [x] Move everything to own org page. Too busy.
- [x] Create
  - [x] Do not allow to subscribe actions multiple times to the same event
- [x] Delete
- [x] For superadmin (can subscribe to any non-org action)
  - [x] List only system event types
  - [x] Create
    - [x] Only if not used in any event subscriptions
  - [x] Delete

### Event Actions

- [x] Create
- [x] Details
  - [x] Show what subscriptions used in for org
  - [x] Show what subscriptions used in for superadmin
- [x] Edit
- [x] Delete
  - [x] Only if not used in any event subscriptions
- [x] Encrypt configuration
- [x] Move to organization UI as only place to create these
  - [x] Remove `tenant_id` field
- [x] Add node on superadmin / system page about how there is an org-specific UI, too
- [x] ~~Assign to tenants for use in detection events~~ -> moved to #812 
- [x] Move edit onSubmit to proxy of sorts
- [x] For superadmins
  - [x] Create
  - [x] Details
  - [x] Edit
  - [x] Delete
    - [x] Only if not used in any event subscriptions

### Event List

- [x] Table
- [x] Pagination
- [x] Filters
  - [x] Event Type (`SYSTEM`/`DETECTION`)
- [x] Explain what this does and that alerts are managed in more details in the alerts area
- [x] Show for org admin
  - [x] Pagination
  - [x] Table
  - [x] Help text
