### ISSUE TITLE
Finish 802.11 Alerting

### ISSUE THREAD

**Issue by lennartkoopmann** [lennartkoopmann/nzyme#827]
- [x] DetectionAlertService
  - [x] Update `last_seen` in case of same alert re-appearing
  - [x] Store Periods of activity
- [ ] Extend notification service to work with detection alerts
  - [x] Include nullable `dot11_monitored_networks` field
  - [x] Allow to subscribe action to all detection alerts
    - [x] Do not allow double-subs
  - [x] Show org selector for super admins
  - [x] Do not allow double-subscriptions
  - [x] Show on events page / table
- [x] Show active alerts on monitoring page
  - [x] Table
  - [x] Details
- [x] Allow to mark alert as resolved. Set `resolved=true`, re-trigger sets `resolved=false`
  - [x] Adapt `isActive` checks
  - [x] From alert details
  - [x] From alert table
- [x] Always require org and tenant IDs
  - [x] UI
  - [x] Adapt permission checks in REST resources
- [x] Change detection logic to real-time approach for better performance
  - [x] Check if monitored network is active
  - [x] Network Monitor alerts
    - [x] DOT11_MONITOR_BSSID,
    - [x] DOT11_MONITOR_CHANNEL,
    - [x] DOT11_MONITOR_SECURITY_SUITE,
    - [x] DOT11_MONITOR_FINGERPRINT,
    - [x] DOT11_MONITOR_SIGNAL_TRACK,
  - [x] Tap-submitted alerts
    - [x] Pwnagotchi
  - [x] Bandit detector alerts
    - [x] Bandit detection
- [x] Alerting UI
  - [x] List all alerts
  - [x] Pagination
  - [x] Delete alerts
    - [x] From details page
    - [x] From alerts table
  - [ ] ~~Filter by alert type~~ -> #900
  - [x] Alert details page
    - [x] When was the alert active / state changes
    - [x] Link to monitored network
      - [x] If user has `dot11_monitoring_manage` permission
      - [x] Work with now deleted networks
    - [x] Different details, based on alert type
      - [x] DOT11_MONITOR_BSSID,
      - [x] DOT11_MONITOR_CHANNEL,
      - [x] DOT11_MONITOR_SECURITY_SUITE,
      - [x]  DOT11_MONITOR_FINGERPRINT,
      - [x]  DOT11_MONITOR_SIGNAL_TRACK,
      - [x] DOT11_BANDIT_CONTACT
        - [x] Pwnagotchi 
  - [x] Only show relevant links when permissions for user exist
- [x] Port existing v1.x alerts (Move to additional tickets as fit)
  - [x] From existing network monitoring engine
    - [x] Unexpected BSSID
    - [x] Unexpected security suite
    - [ ] ~~Unexpected security protocol~~ -> #875
    - [x] Unexpected channel
    - [x] Unexpected fingerprint
    - [x] Unexpected signal tracks
  - [ ] ~~Beacon rate anomaly~~ -> #875
  - [x] Pwnagotchi advertisement
  - [x] Bandit contact
    - [x] Add remaining bandits
      - [x] Pineapple Nano
        - [x] Management AP
        - [x] PineAP
        - [x] Open AP
      - [x] Pineapple Tetra
        - [x] Management AP
        - [x] PineAP
        - [x] Open AP
      - [x] Pineapple Mark VII
        - [x] Management AP
        - [x] PineAP
        - [x] Open AP
    - [x] Show supported bandits
  - [ ] ~~Deauth flood~~ -> #875
- [ ] ~~New alerts (Move to additional tickets as fit)~~ -> #875
  - [ ] ~~Location / Triangulation~~ -> #875
  - [ ] ~~Beacon Timestamp wildly different (consider restarts)~~ -> #875
  - [ ] ~~Beacon interval different~~ -> #875
  - [ ] ~~Access points advertising with probe responses only~~ -> #875
  - [ ] ~~Infrastructure type different~~ -> #875
  - [ ] ~~Any ad-hoc network seen~~ -> #875
  - [ ] ~~Unusual amounts of retries between two stations~~ -> #875
  - [ ] ~~Unusual amount of probe requests from single client~~ -> #875
  - [ ] ~~Delta between signal strengths of SSIDs per BSSID ~~ -> #875
- [x] Test
  - [x] Signal track detection
  - [x] Superadmin
  - [x] Org admin
  - [x] Tenant user
  - [x] Monitored networks
    - [x] Superadmin
    - [x] Org admin
    - [x] Tenant user
- [x] Update documentation
  - [x] Track detector runs over last 8 hours of data, over monitored channels, all monitored BSSIDs
  - [x] Read all to confirm
